23A8 = { team = 1,  flavor = "A" }
23BB = { team = 2,  flavor = "A" }
2452 = { team = 3,  flavor = "A" }
24C8 = { team = 4,  flavor = "A" }
24C9 = { team = 5,  flavor = "A" }
24CF = { team = 6,  flavor = "A" }
24E7 = { team = 7,  flavor = "A" }
2546 = { team = 8,  flavor = "A" }
259B = { team = 9,  flavor = "A" }
26A1 = { team = 10, flavor = "A" }
26D5 = { team = 11, flavor = "A" }
26E6 = { team = 12, flavor = "A" }
26ED = { team = 13, flavor = "A" }
270D = { team = 14, flavor = "A" }
2811 = { team = 15, flavor = "A" }
2984 = { team = 16, flavor = "A" }
29FC = { team = 17, flavor = "A" }
2A0B = { team = 18, flavor = "A" }
2A4A = { team = 19, flavor = "A" }
2AD8 = { team = 20, flavor = "A" }
2AF0 = { team = 21, flavor = "A" }
7827 = { team = 23, flavor = "A" }
78BD = { team = 24, flavor = "A" }
79C2 = { team = 25, flavor = "A" }
7AD4 = { team = 26, flavor = "A" }
7ADD = { team = 27, flavor = "A" }
7D7B = { team = 28, flavor = "A" }
7E00 = { team = 29, flavor = "A" }
7E4C = { team = 30, flavor = "B" }
7E4E = { team = 31, flavor = "B" }
7E51 = { team = 32, flavor = "B" }
7E56 = { team = 33, flavor = "B" }
7E6A = { team = 34, flavor = "B" }
7E97 = { team = 35, flavor = "B" }
7EA2 = { team = 36, flavor = "B" }
7EB0 = { team = 37, flavor = "B" }
7EB1 = { team = 38, flavor = "B" }
7EC0 = { team = 39, flavor = "B" }
7EC5 = { team = 40, flavor = "C" }
7ED0 = { team = 41, flavor = "C" }
7EDD = { team = 42, flavor = "C" }
7EE9 = { team = 43, flavor = "C" }
7EED = { team = 44, flavor = "C" }
7EF8 = { team = 45, flavor = "C" }
7F14 = { team = 46, flavor = "C" }
7F29 = { team = 47, flavor = "C" }
7FB9 = { team = 48, flavor = "C" }

7E47 = { team = 49, flavor = "C" }

568B = { note = "test device, red color" }
78E7 = { note = "test device, blue color" }
94A0 = { note = "test device, slab type" }
9799 = { note = "test device, slab type" }
97EA = { note = "test device, slab type" }
ABC0 = { note = "test device, darker board" }
