23a8 = { team = 1 }
23bb = { team = 2 }
2452 = { team = 3 }
24c8 = { team = 4 }
24c9 = { team = 5 }
24cf = { team = 6 }
24e7 = { team = 7 }
2546 = { team = 8 }
259b = { team = 9 }
26a1 = { team = 10 }
26d5 = { team = 11 }
26e6 = { team = 12 }
26ed = { team = 13 }
270d = { team = 14 }
2811 = { team = 15 }
2984 = { team = 16 }
29fc = { team = 17 }
2a0b = { team = 18 }
2a4a = { team = 19 }
2ad8 = { team = 20 }
2af0 = { team = 21 }
568b = { team = 22 }
7827 = { team = 23 }
78bd = { team = 24 }
78e7 = { team = 25 }
79c2 = { team = 26 }
7ad4 = { team = 27 }
7add = { team = 28 }
7e00 = { team = 29 }
7e3d = { team = 30 }
7e47 = { team = 31 }
7e4c = { team = 32 }
7e4e = { team = 33 }
7e51 = { team = 34 }
7e56 = { team = 35 }
7e6a = { team = 36 }
7e97 = { team = 37 }
7ea2 = { team = 38 }
7eb0 = { team = 39 }
7eb1 = { team = 40 }
7ec0 = { team = 41 }
7ec5 = { team = 42 }
7ed0 = { team = 43 }
7edd = { team = 44 }
7ee9 = { team = 45 }
7eed = { team = 46 }
7ef8 = { team = 47 }
7f14 = { team = 48 }
7f29 = { team = 49 }
7fb9 = { team = 50 }
94a0 = { team = 51 }
9799 = { team = 52 }
97ea = { team = 53 }
abc0 = { team = 54 }
