# Test devices assigned to teams

568B = { team = 11, flavor = "A", note = "test device, red color" }
78E7 = { team = 12, flavor = "A", note = "test device, blue color" }
94A0 = { team = 13, flavor = "B", note = "test device, slab type" }
9799 = { team = 14, flavor = "B", note = "test device, slab type" }
97EA = { team = 15, flavor = "C", note = "test device, slab type" }
ABC0 = { team = 16, flavor = "C", note = "test device, darker board" }
